### PR TITLE
update blog post links

### PR DESCRIPTION
**Pull request by dv336699**
The guid still points to the old wordpress blog tho.

### CODE REVIEW

**Comment by flovilmart** [comment]
where's the guid used?

**Comment by montymxb** [comment]
It might be something that would be used if we generated an rss/atom feed, just a guess.

**Comment by flovilmart** [comment]
Ah alright, probably there’s something like that for jekyll.

**Comment by montymxb** [comment]
I don't really think we ever utilized it then, this is probably fine and keeps things in line with the current domain.

**Pull request merged**
