### PR TITLE
March update blog post

### PR DESCRIPTION
**Pull request by TomWFox**
I've started to write a 'March update' blog post with the following main focus areas:
- The new community forum
- The departure of [@flovilmart](https://twitter.com/flovilmart) + new leadership
- I'm new, how can I get involved
- A summary of the last year for the Parse Platform
- What are we working?

I've never written a blog post before (certainly not for a open source project) so please suggest any changes however big or small - although preferably not "scrap the whole post, it's terrible" ;)

### CODE REVIEW

**Review by acinader — APPROVED** [review]
awesome!  feel free to merge it when you're ready.

**Comment by TomWFox** [comment]
@acinader Thanks, I don't have write access so I can't merge. Although I was also planning to wait a few days as I'm working on adding a tweet button for blog posts.

**Comment by acinader** [comment]
k.  just let me know when you want me to merge.  Glad to do this now and then look at the next pr, or wait. up to you.

**Comment by TomWFox** [comment]
@acinader I've finished #15 which adds the tweet button, so it would be great if you could merge that and this one too.

BTW - I made a couple minor changes on this post since your review.

**Pull request merged**
