### PR TITLE
(Article) PHP SDK Release 1.4.0

### PR DESCRIPTION
**Pull request by montymxb**
An article for release 1.4.0 of the php sdk.

### CODE REVIEW

**Review by flovilmart — APPROVED** [review]

**Comment by montymxb** [comment]
It looks like the build failed in travis and was never published :/ , I'm looking into it now.

**Comment by montymxb** [comment]
Yeah, @flovilmart looks like deployment to gh-pages is [failing for some reason](https://travis-ci.org/parse-community/blog/jobs/312396751#L2911). Odd because the last activity on gh-pages was a similar deployment from travis, so either something is up with travis or the token is goofed somehow?

**Comment by flovilmart** [comment]
I regenerated the token (1 token / repo) and we'll see :)

**Comment by montymxb** [comment]
Awesome, deploy finished and it's up now 👍 .

**Pull request merged**
