### PR TITLE
(Article) PHP SDK Release 1.3.0

### PR DESCRIPTION
**Pull request by montymxb**
Article for the new sdk version **1.3.0** that was released yesterday.

### CODE REVIEW

**Comment by montymxb** [comment]
@flovilmart cool if we bring this in?

**Comment by montymxb** [comment]
@flovilmart sorry to bump again, are we interested in this or do we want a different kind of content for articles?

**Comment by flovilmart** [comment]
Nope that's great! Sorry, too many things on my plate to cover :/

**Comment by montymxb** [comment]
Awesome! And yeah I can imagine, I may just poke you from time to time to remind if anything is outstanding. But, this takes care of the old stuff that even I nearly forgot about haha.

**Pull request merged**
